version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
  publish:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - cd circleci-demo
      - run: pwd | echo 
      - run: echo "Hello world" > hello.txt
      - run: |
          git config credential.helper 'cache --timeout=120'
          git config user.email "patricia.ortegon@gmail.com"
          git config user.name "patylu001"
          git add .
          git commit -m "Update via CircleCI"
          git push -q https://patylu001:$GITHUB_TOKEN@github.com/patylu001/circleci-demo.git $CIRCLE_BRANCH
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish
